Embedding Videos and Images: Styles
Kingobaino1/YouTube-Project pull request #1
Opened 2020-08-14 17:24 UTC by Kingobaino

## YouTube clone Embedding Videos and Images: Styles
 In this project,
- Added styles to the nav-bar, videos, side-bar, and footer.

2020-08-14 21:35 UTC, kevcap requested changes
# [STATUS] CHANGES REQUIRED♻️

### Hi team, you guys did a very good job so far!
#### I can see that you guys are working hard at this project, and you're almost done, there are just some required changes* that you guys have to implement in order to proceed:

[REQUIRED CHANGES]
- [ ] Check usage of [semantic HTML](https://www.w3schools.com/html/html5_semantic_elements.asp)  (e.g. use of the `<video>` tag for the content of wraps a video or `<iframe>`.) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/semantic_html_requirement.png) from Pathwright)
- [ ] Add a descriptive text to your pull request 
- [ ] Remove all the unecessary file (e.g. index.js)
- [ ] Put your `style.css` file in a css folder
- [ ] Take a look at your readme file, make it as professional as possible. Remove that "etc" at the Acknowledgments section, and Remove any non-applicable section;
![image](https://user-images.githubusercontent.com/56762529/90293669-02e25900-de5b-11ea-8b2a-21b2c294c702.png)
![image](https://user-images.githubusercontent.com/56762529/90293703-15f52900-de5b-11ea-8797-740bce859613.png)

- [ ] Make your description section [1] more similar to the original one;
- [ ] Make your navbar [2] more similar to the original one;
- [ ] Remove that border in your recommended videos section [3];
- [ ] Remove that border that wraps your page [4];
![image](https://user-images.githubusercontent.com/56762529/90292291-02948e80-de58-11ea-901d-19b88e764826.png)

- [ ] Your code is throwing some errors and warnings at the [HTML5 Validator](https://validator.w3.org/nu/#textarear), please fix them
![image](https://user-images.githubusercontent.com/56762529/90293207-f01b5480-de59-11ea-83b8-d5db3cd572cc.png)

- [ ] Remove all the unnecessary repeated CSS code ([Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/))
![image](https://user-images.githubusercontent.com/56762529/90293288-1b05a880-de5a-11ea-9dd0-42d5b02b2d2d.png) 
(This image is just an example, but you should look for repeated code and remove it whenever possible)
Tip: Create one only class like this: `.d-inline { display: inline-block }` and use that same class when you need it.


Tip: Always use the HTML5 Validator in your projects

[OPTIONAL CHANGES]
- [ ] Add a comments section
- [ ] Use the [`<nav>` tag](http://html5doctor.com/nav-element/) for the major navigation links

**Please make the required changes and resubmit for a new code review once you are ready**

As always, I wish you all the very best and see you both at the top🚀

  

<hr>

👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

  
<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

2020-08-14 21:35 UTC, kevincappuccino commented on README.md
> +### Deployment
[README.MD] Remove any non-applicable section

2020-08-14 21:35 UTC, kevincappuccino commented on README.md
> +- etc
[README.MD] Make it more professional. e.g. remove that "etc"

2020-08-14 21:35 UTC, kevincappuccino commented on index.html
>          <section class="video">
Use semantic HTML5. e.g. `<video>`

2020-08-14 21:35 UTC, kevincappuccino commented on index.html
> +                <p><strong>Contributing to Open Source Part II: The Real Way</strong><br>
Don't use the <strong> tag to make regular text bold, use CSS instead. [The HTML Strong Importance Element (<strong>) indicates that its contents have strong importance, seriousness, or urgency. Browsers typically render the contents in bold type.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strong)

2020-08-14 21:35 UTC, kevincappuccino commented on index.html
> +                    <span class="text-font"><small>imtiana<br>
Don't use the <strong> tag to make regular text bold, use CSS instead. [The HTML Strong Importance Element (<strong>) indicates that its contents have strong importance, seriousness, or urgency. Browsers typically render the contents in bold type.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strong)

2020-08-14 21:35 UTC, kevincappuccino commented on index.html
> +                    <span class="text-font"><small>iBasskung<br>
Don't use the <strong> tag to make regular text bold, use CSS instead. [The HTML Strong Importance Element (<strong>) indicates that its contents have strong importance, seriousness, or urgency. Browsers typically render the contents in bold type.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strong)

2020-08-14 21:35 UTC, kevincappuccino commented on index.html
> +                <p><strong>REST API concepts and examplesy</strong><br>
Don't use the <strong> tag to make regular text bold, use CSS instead. [The HTML Strong Importance Element (<strong>) indicates that its contents have strong importance, seriousness, or urgency. Browsers typically render the contents in bold type.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strong)

2020-08-14 21:35 UTC, kevincappuccino commented on index.html
> +                <p><strong>GitHub - Why Microsoft Paid $7.5B for the Future of Software! - A Case</strong><br>
Don't use the <strong> tag to make regular text bold, use CSS instead. [The HTML Strong Importance Element (<strong>) indicates that its contents have strong importance, seriousness, or urgency. Browsers typically render the contents in bold type.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strong)

2020-08-14 21:35 UTC, kevincappuccino commented on index.html
> +                <p><strong>How to create a 3D Terrain with Google Maps and height maps in Photoshop</strong><br>
Don't use the <strong> tag to make regular text bold, use CSS instead. [The HTML Strong Importance Element (<strong>) indicates that its contents have strong importance, seriousness, or urgency. Browsers typically render the contents in bold type.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strong)

2020-08-14 21:35 UTC, kevincappuccino commented on index.html
> +                <p><strong>How to create a 3D Terrain with Google Maps and height maps in Photoshop</strong><br>
Don't use the <strong> tag to make regular text bold, use CSS instead. [The HTML Strong Importance Element (<strong>) indicates that its contents have strong importance, seriousness, or urgency. Browsers typically render the contents in bold type.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strong)

2020-08-14 21:35 UTC, kevincappuccino commented on index.html
> +                <p><strong>Top 10 Linux Job Interview Question</strong><br>
Don't use the <strong> tag to make regular text bold, use CSS instead. [The HTML Strong Importance Element (<strong>) indicates that its contents have strong importance, seriousness, or urgency. Browsers typically render the contents in bold type.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strong)

2020-08-14 21:35 UTC, kevincappuccino commented on index.html
> +                <p><strong>Running an SQL Injection Attack - Computerphile</strong><br>
Don't use the <strong> tag to make regular text bold, use CSS instead. [The HTML Strong Importance Element (<strong>) indicates that its contents have strong importance, seriousness, or urgency. Browsers typically render the contents in bold type.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strong)

2020-08-14 21:35 UTC, kevincappuccino commented on index.html
> +                <p><strong>Contributing to Open Source Part II: The Real Way</strong><br>
Don't use the <strong> tag to make regular text bold, use CSS instead. [The HTML Strong Importance Element (<strong>) indicates that its contents have strong importance, seriousness, or urgency. Browsers typically render the contents in bold type.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strong)

2020-08-14 21:35 UTC, kevincappuccino commented on index.html
> +                <p><strong>'How to Get a Job at the Big 4 - Amazon, Facebook, Google & Microsoft' by</strong><br>
Don't use the <strong> tag to make regular text bold, use CSS instead. [The HTML Strong Importance Element (<strong>) indicates that its contents have strong importance, seriousness, or urgency. Browsers typically render the contents in bold type.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strong)

2020-08-14 21:35 UTC, kevincappuccino commented on index.html
> +                <p><strong>Programming in Visual Basic .Net How to Connect Access Database to</strong><br>
Don't use the <strong> tag to make regular text bold, use CSS instead. [The HTML Strong Importance Element (<strong>) indicates that its contents have strong importance, seriousness, or urgency. Browsers typically render the contents in bold type.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strong)

2020-08-14 21:35 UTC, kevincappuccino commented on index.html
> +                <p><strong>REST API concepts and examplesy</strong><br>
Don't use the <strong> tag to make regular text bold, use CSS instead. [The HTML Strong Importance Element (<strong>) indicates that its contents have strong importance, seriousness, or urgency. Browsers typically render the contents in bold type.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strong)

2020-08-14 21:35 UTC, kevincappuccino commented on index.html
> +                <p><strong>GitHub - Why Microsoft Paid $7.5B for the Future of Software! - A Case</strong><br>
Don't use the <strong> tag to make regular text bold, use CSS instead. [The HTML Strong Importance Element (<strong>) indicates that its contents have strong importance, seriousness, or urgency. Browsers typically render the contents in bold type.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strong)

2020-08-14 21:35 UTC, kevincappuccino commented on index.html
> +                <p><strong>How to create a 3D Terrain with Google Maps and height maps in Photoshop</strong><br>
Don't use the <strong> tag to make regular text bold, use CSS instead. [The HTML Strong Importance Element (<strong>) indicates that its contents have strong importance, seriousness, or urgency. Browsers typically render the contents in bold type.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strong)

2020-08-14 21:35 UTC, kevincappuccino commented on index.html
> +                <p><strong>How to create a 3D Terrain with Google Maps and height maps in Photoshop</strong><br>
Don't use the <strong> tag to make regular text bold, use CSS instead. [The HTML Strong Importance Element (<strong>) indicates that its contents have strong importance, seriousness, or urgency. Browsers typically render the contents in bold type.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strong)

2020-08-17 23:41 UTC, Kingobaino1 commented
## In this Embedding videos and images project
- we used the unordered list to group  different sections
- we styled different sections on a separate css file.
- we embedded a YouTube video and used images as the thumbnails.

2020-08-18 03:05 UTC, kitpao requested changes
# 👋 Hello @Kingobaino1 and @abmasadullah 

Good job fixing most of the previous TSE required changes, your page is looking good 🌟 

However you are only missing 3 issues, please check them below 🔽 

- Friendly reminder: Be careful with your GitHub Flow, for next time, only touch the master branch for setting up your repo, everything else should be done in the feature-branch

### ♻️ Status: Your project requires some additional changes ♻️
➡️ Please request another review once you are ready 📝 
___
##### 👉 If you have any doubts you can contact me in slack as @kitpao

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-08-18 03:05 UTC, kitpao commented on README.md
> +**Log on to the Github and clone the repository to our local machine.**
- [ ] **OPTIONAL** I think you meant **your** local machine.

2020-08-18 03:05 UTC, kitpao commented on README.md
> +- Linkedin: [linkedin](https://www.linkedin.com/in/abmasadullah)
- [ ] Instead of githubhandle, please change it to your own username, like `Github: [@abmasadullah](https://github.com/abmasadullah)`, same with the others, so it doesn't look that you didn't customize your template

2020-08-18 03:05 UTC, kitpao commented on index.html
> +            </div>
- [ ] I know your navbar looks like the sample given, but you should take care of Microverse's specific requirements in Pathwright:
![image](https://user-images.githubusercontent.com/53256139/90464438-ea7c7380-e0d2-11ea-9425-6982acfa3cfe.png)

2020-08-18 03:05 UTC, kitpao commented on css/style.css
> +}
- [ ] The purpose of making a class with your repeated rules as suggested by previous TSE is so they won't be repeated again in your CSS, to follow good coding practices (DRY rule).  Please delete repeated rules and make necessary changes

  👉 I'll leave you with an example

  You can use multiple classes for any HTML element, so for example,

  If you use these lines in many classes:
  ```
  color: #fff;
  background-color: #000;
  ```
  and you use it for .class1, .class2, and .class3 
  you can put them inside a single class called for example "common-class" so it will look like this:
  **CSS**
  ```
  .class1 {
    font-size: 24px;
  }
  .class2 {
    font-size: 30px;
  }
  .class3 {
    font-size: 10px;
  }
  .common-class {
    color: #fff;
    background-color: #000
  }
  ```
  and in **HTML**:
  ```
  <nav class="class1 common-class">  <!-- this will have font size of 24px, color of #fff and background-color of #000 -->
  ...
  <div class="class2 common-class">  <!-- this will have font size of 30px, color of #fff and background-color of #000 -->
  ...
  <footer class="class3 common-class">   <!-- this will have font size of 10px, color of #fff and background-color of #000 -->
  ...
  ```

2020-08-18 15:30 UTC, Kingobaino1 commented
We can not find the upload-icon image and that is the reason why we have to use the icon from font-awesome.

2020-08-18 16:36 UTC, MuriloRoque requested changes
# Status: Changes requested :red_circle: 

## Hello @Kingobaino and @abmasadullah :wave: 

Thank you for fixing your README file and CSS after the last TSE's suggestion!

However, we still need to fix [this](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/icons_requirement.png) requirement she asked, you need to embed two more images in your navbar. Currently, there's only one:

![Screenshot from 2020-08-18 13-35-02](https://user-images.githubusercontent.com/59691171/90540509-b0a18080-e157-11ea-8d38-7edcbf681483.png)

## Kindly make the requested changes and submit for another review, please :pray: 

## I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-08-18 18:03 UTC, kevcap approved these changes
# [STATUS] PROJECT APPROVED 🍾

### Nice job implementing the required changes! As you met the last TSE's requirements, I'll approve this project! Congrats team!!!! 👏👏👏👏👏
![giphy4](https://user-images.githubusercontent.com/56762529/90549075-54912900-e164-11ea-9567-84b4c00ff7a0.gif)

You guys can now merge these changes. I wish the very best and see you all at the top🚀



<hr>





👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

2020-08-18 19:02 UTC, merged